### ISSUE TITLE
Subscribing to topics with wildcards never triggers callback

### ISSUE THREAD

**Issue by NotionalLabs** [plapointe6/EspMQTTClient#29] opened 2019-09-29 17:41 UTC
I just discovered if you wish to subscribe to a topic using wildcards, the check to pull the callback out of the subscription list only looks for exact equivalence so it will never fire.

e.g. espmqtt client subs to `my/test/topic/+`, another client pubs to `my/test/topic/bug`; in `EspMQTTClient::mqttMessageReceivedCallback`, `mTopicSubscriptionList[i].topic` will contain `my/test/topic/+`, and topic will contain `my/test/topic/bug`.

**Comment by plapointe6** [comment] 2019-10-02 23:38
Hello,

It's related to #12

Unfortunatly, wildcards are currently not supported.
I added this to the todo list, but I havent worked on this yet.

I will close this issue as it's a duplicate of #12 that request the wildcards functionnality.

Regards.

**Closed by plapointe6** 2019-10-02 23:38 UTC
